# Generated by Django 3.2.9 on 2022-03-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_rename_towel_htowel_blaundry_towel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blaundry',
            old_name='pent',
            new_name='pant',
        ),
    ]
