# Generated by Django 3.2.9 on 2022-03-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glaundry',
            old_name='pent',
            new_name='pant',
        ),
        migrations.RenameField(
            model_name='glaundry',
            old_name='towel_htowel',
            new_name='towel',
        ),
    ]
